SportsStore/Models/Cart.cs
using System.Collections.Generic;
using System.Linq;

namespace SportsStore.Models {
    public class Cart {
        private readonly List<CartLine> _line = new();

        public virtual IEnumerable<CartLine> Lines => _line;

        public virtual void AddItem(Product product, int quantity) {
            var cartLine = _line.FirstOrDefault(p => p.Product.ProductId == product.ProductId);

            if (cartLine == null)
                _line.Add(new CartLine {
                    Quantity = quantity,
                    Product = product
                });
            else
                cartLine.Quantity += quantity;
        }

        public virtual void RemoveAll(Product product) {
            _line.RemoveAll(p => p.Product.ProductId == product.ProductId);
        }


        public virtual void Remove(Product product) {
            var line = _line.Find(c => c.Product.ProductId == product.ProductId);
            if (line == null) return;
            if (line.Quantity > 1)
                line.Quantity--;
            else if (line.Quantity == 1) RemoveAll(product);
        }

        public virtual decimal CalculateTotalPrice() {
            return _line.Sum(l => l.Product.Price * l.Quantity);
        }


        public virtual void Clear() {
            _line.Clear();
        }
    }

    public class CartLine {
        public int CartLineId { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

SportsStore/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers {
    public class CartController : Controller {
        public CartController(IProductRepository productRepository, Cart cartService) {
            ProductRepository = productRepository;
            CartService = cartService;
        }

        private IProductRepository ProductRepository { get; }
        private Cart CartService { get; }

        public ViewResult Index(string returnUrl) {
            return View(new CartIndexViewModel {ReturnUrl = returnUrl, Cart = CartService});
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl) {
            var product = ProductRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null) CartService.AddItem(product, 1);
            return RedirectToAction("Index", new {returnUrl});
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl) {
            var product = ProductRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null) CartService.Remove(product);
            return RedirectToAction("Index", new {returnUrl});
        }

        public RedirectToActionResult ClearCart(string returnUrl) {
            CartService.Clear();
            return RedirectToAction("Index", new CartIndexViewModel {Cart = CartService, ReturnUrl = returnUrl});
        }
    }
}

SportsStore/Controllers/OrderController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Controllers {
    public class OrderController : Controller {
        public OrderController(IOrderRepository orderRepository, Cart cart) {
            OrderRepository = orderRepository;
            CartService = cart;
        }

        private IOrderRepository OrderRepository { get; }
        private Cart CartService { get; }

        [Authorize]
        public ViewResult List() {
            return View(OrderRepository.Orders.Where(o => !o.Shipped));
        }

        [Authorize]
        [HttpPost]
        public IActionResult MarkShipped(int orderId) {
            var order = OrderRepository.Orders.FirstOrDefault(o => o.OrderId == orderId);
            if (order != null) {
                order.Shipped = true;
                OrderRepository.SaveOrder(order);
            }

            return RedirectToAction("List");
        }

        [HttpGet]
        public ViewResult Checkout() {
            return View(new Order());
        }

        [HttpPost]
        public IActionResult Checkout(Order order) {
            if (!CartService.Lines.Any()) ModelState.AddModelError("", "Sorry, your cart is empty!");

            if (!ModelState.IsValid) return View(order);

            order.Lines = CartService.Lines.ToArray();
            OrderRepository.SaveOrder(order);
            return RedirectToAction("Completed");
        }

        public ViewResult Completed() {
            CartService.Clear();
            return View();
        }
    }
}

SportsStore/Views/Cart/Index.cshtml
@model CartIndexViewModel

<h2>
    Your cart
</h2>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>Quantity</th>
        <th>Item</th>
        <th class="text-right">Price</th>
        <th class="text-right">Subtotal</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var line in Model.Cart.Lines) {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Product.Name</td>
            <td class="text-right">@line.Product.Price.ToString("c")</td>
            <td class="text-right">
                @((line.Quantity * line.Product.Price).ToString("c"))
            </td>
            <td>
                <form asp-controller="Cart" asp-action="RemoveFromCart">
                    <input type="hidden" name="ProductID" value="@line.Product.ProductId">
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl">
                    <input type="submit" value="Remove" class="btn btn-sm btn-danger"/>
                </form>
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3" class="text-center">Total:</td>
        <td class="text-center">
            @Model.Cart.CalculateTotalPrice().ToString("c")
        </td>
    </tr>
    </tfoot>
</table>
<div class="text-center">
    <span>
        <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
        <a class="btn btn-primary" asp-action="ClearCart" asp-route-returnUrl="@Model.ReturnUrl">Clear cart</a>
        <a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">Checkout</a>
    </span>
</div>