SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components {
    public class CartSummaryViewComponent : ViewComponent {
        public CartSummaryViewComponent(Cart cartService) {
            CartService = cartService;
        }

        private Cart CartService { get; }

        public IViewComponentResult Invoke() {
            return View(CartService);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components {
    public class NavigationMenuViewComponent : ViewComponent {
        public NavigationMenuViewComponent(IProductRepository productRepository) {
            ProductRepository = productRepository;
        }

        private IProductRepository ProductRepository { get; }

        public IViewComponentResult Invoke() {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(ProductRepository
                .Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

SportsStore/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers {
    public class CartController : Controller {
        public CartController(IProductRepository productRepository, Cart cartService) {
            ProductRepository = productRepository;
            CartService = cartService;
        }

        private IProductRepository ProductRepository { get; }
        private Cart CartService { get; }

        public ViewResult Index(string returnUrl) {
            return View(new CartIndexViewModel {ReturnUrl = returnUrl, Cart = CartService});
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl) {
            var product = ProductRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null) CartService.AddItem(product, 1);
            return RedirectToAction("Index", new {returnUrl});
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl) {
            var product = ProductRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null) CartService.Remove(product);
            return RedirectToAction("Index", new {returnUrl});
        }

        public RedirectToActionResult ClearCart(string returnUrl) {
            CartService.Clear();
            return RedirectToAction("Index", new CartIndexViewModel {Cart = CartService, ReturnUrl = returnUrl});
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float: right;">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductId" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductId"/>
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <span class="card-text p-1">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float: right">
                Add to cart
            </button>
        </span>
    </form>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/bootstrap.min.css">
    <script asp-href-include="lib/jquery/jquery.min.js"></script>
    <script asp-href-include="lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script asp-href-include="lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red; background-color: #fefefe;
        }
    </style>
</head>
<body class="m-1 p-1">
<div class="bg-info p-2 row">
    <div class="bg-info p-2">
        <h4>@ViewBag.Title</h4>
    </div>
    <div class="col-2">
        <a class="btn btn-primary" asp-controller="Account" asp-action="Logout">Log out</a>
    </div>
</div>
@if (TempData["message"] != null) {
    <div class="alert alert-success mt-1">@TempData["message"]</div>
}
@RenderBody()
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/bootstrap.min.css"/>
    <title>SportsStore</title>
</head>
<body>
<div class="navbar navbar-expand-sm bg-primary" role="navigation">
    <label style="width: 10%; vertical-align: center">SPORTS STORE</label>
    <div class="text-right" style="width: 90%">
        @await Component.InvokeAsync("CartSummary")
    </div>
</div>
<div class="row m-1 p-1">
    <div id="categories" class="col-3">
        @await Component.InvokeAsync("NavigationMenu")
    </div>
    <div class="col-9">
        @RenderBody()
    </div>
</div>
</body>
</html>